#+title: On Emacs

** Errors and simple fixed for my Emacs 29.1 installation (Dec 8, 2023)
1) After upgrading to 29.1 had some issues with Marginalia, which caused vertico to not function properly. Reinstalling Marginalia sorted the issue.
2) Next, I had issues with the major mode not being interpreted at all. Everything was being read as Fundamental. I realized I had to edit ~auto-add-alist~.
   - I found this link with file extensions and the associated modes. Added the value to my init file.
   - While wrangling with the above, I also discovered the discussion around tree-sitter so installed that as well.
3) Then I was hitting ~Symbol's value as void...~ triggered by Magit. So, I reinstalled Magit, restarted EMACS.

** PyMC/PyTensor/BLAS warning on Emacs (Jan 18, 2024)
1) Importing pytensor in a python script inside EMACS was giving warning ~Using NumPy C-API based implementation for BLAS functions.~
2) Interestingly, this was not showing up when I was firing python on the ~terminal~ and importing pytensor.
3) The fix was simple and as below:
   a) started python in the terminal, then ~import pytensor as pt~ and then ~pt.config.blas__ldflags~. Since pytensor was working in the terminal fired python, the code above produced a string ~-L/Users/uname/opt/miniconda3/envs/pymc_env/lib -lmkl_core -lmkl_rt -lmkl_intel_thread -liomp5 -lpthread -Wl,-rpath,/Users/uname/opt/miniconda3/envs/pymc_env/lib~
   b) created ~.pytensorrc~ file in $HOME and inserted the string above 
      ~[blas]~  
      ~ldflags=-L/Users/uname/opt/miniconda3/envs/pymc_env/lib -lmkl_core -lmkl_rt -lmkl_intel_thread -liomp5 -lpthread -Wl,-      rpath,/Users/uname/opt/miniconda3/envs/pymc_env/lib~
This stopped the warning.
